package com.mobile.advance.webservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.10.0
//
// Created by Quasar Development at 22-02-2016
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class objPermiso extends AttributeContainer implements KvmSerializable
{

    
    public String Rol;
    
    public String Aplicacion;
    
    public String Usuario;

    public objPermiso ()
    {
    }

    public objPermiso (Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("Rol"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.Rol = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this.Rol = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("Aplicacion"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.Aplicacion = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this.Aplicacion = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("Usuario"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.Usuario = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this.Usuario = (String)obj;
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.Rol!=null?this.Rol:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.Aplicacion!=null?this.Aplicacion:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.Usuario!=null?this.Usuario:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 3;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Rol";
            info.namespace= "http://tempuri.org/";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Aplicacion";
            info.namespace= "http://tempuri.org/";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Usuario";
            info.namespace= "http://tempuri.org/";
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

}
